name: Python application tests

on: [push, pull_request] # Run on push events and pull requests

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v3 # Check out your repository code
    - name: Set up Python 3.x # Choose your Python version
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # Or your desired version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install dependencies from your file
    - name: Test with pytest
      run: |
        pytest # Run your tests
