
name: Python application tests

on: [push, pull_request] # Run on push events and pull requests

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v3 # Check out your repository code
    - name: Set up Python 3.x # Choose your Python version
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # Or your desired version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install dependencies from your file
    - name: Test with pytest
      run: |
   - name: Pytest summary
  # You may pin to the exact commit or the version.
  # uses: dariocurr/pytest-summary@c3fc958df714d627256b96b9f2050365d3e122ad
  uses: dariocurr/pytest-summary@v2.4
  with:
    # The pytest extensions to install along pytest
    extensions: # optional
    # The pytest options
    options: # optional
    # The path to the output file to create
    output: # optional
    # The path to the folder containing the tests
    paths: # optional, default is tests
    # Which tests have to be shown in the summary
    show: # optional
          
        pytest # Run your tests
